### ISSUE TITLE
Create a documentation that explains the glue between different entities used to deploy and transform components

### ISSUE THREAD

**Issue by morri-son** [open-component-model/mpas-public-demo#11]
Since the whole story around actions required using definition and configuration files, it makes sense to add some more details in the form of comments inside the configuration files and / or additional parts in the documentation that explain the different sections in the files and especially the "glue" between them, e.g. config referring to resource names in the component descriptors. 

Since the component.yaml is transferred into a component version that has a slightly different schema and finally ends up in the target system with artifacts that are now local to the component descriptor, we may also add some information on that, as otherwise actions like https://github.com/open-component-model/mpas-public-demo/blob/main/00-setup-demo/component-repo-src/main-branch/src/ocm-ctrl/config.yaml#L55 are not clear, when just looking at https://github.com/open-component-model/mpas-public-demo/blob/main/00-setup-demo/component-repo-src/main-branch/componentfile.yaml.

It may make sense to move some or even all of the explanations to a more central place inside the MPAS repos, as they are a central part of understanding the function of mpas on provider and consumer side.

Files that should get more explanation:

* https://github.com/open-component-model/mpas-public-demo/blob/main/00-setup-demo/component-repo-src/main-branch/componentfile.yaml
  * what elements / resources need to be added
    * software artifacts
      * e.g. Docker images (most-likely as references to other oci registries, not as local blobs)
      * e.g. Helm Charts (most-likely as references to helm chart repos, not as local blobs) 
      * config (templates) to describe what can be configured and localized
      * GitOps config
      * documenation / guides / instructions
      * product description
    * what does the component version yaml looks like in the oct registry (after being creating using ocm add cv) of the vendor
    * what does the component descriptor looks like in the target env after pulling all artifacts into the local registry and can be used to programatically work with the content and transform it (like in https://github.com/open-component-model/mpas-public-demo/blob/main/00-setup-demo/component-repo-src/main-branch/src/ocm-ctrl/config.yaml#L51-L57)

* https://github.com/open-component-model/mpas-public-demo/blob/main/00-setup-demo/component-repo-src/main-branch/src/ocm-ctrl/config.yaml#L51-L57
  * configuration
    * defaults
    * rules
    * schema
  * localization
    * files and basic mapping
    * possibility to use CUE for the transformation

* https://github.com/open-component-model/mpas-public-demo/tree/main/00-setup-demo/component-repo-src/main-branch/src/flux
  * explain that files are referred in the config.yaml and just act as a template for the transformation and will only be applied AFTER the transformation. Just looking at them looks like Flux would just apply them like they are.
 
* https://github.com/open-component-model/mpas-public-demo/tree/main/00-setup-demo/component-repo-src/main-branch/src/charts
  * explain why the file is packaged and not just referenced, similar to the podinfo docker image. Maybe give an example for how the resource would be defined in case the helm chart would be referenced in an external helm chart repo.

**Comment by phoban01** [comment]
Thanks for all this detail @morri-son it's very helpful. I think this kind of documentation and detail should live in the MPAS repository and should be published as a dedicated documentation site (in [mdbook](https://rust-lang.github.io/mdBook/) style). 

There are some aspects of what you've outlined above that I would consider "advanced usage" and things we have done in order to construct a demo environment; were we to cover all these things in the context of a demo it would no longer really serve the purpose of giving the reader a sense of how to use the system. The focus here should not be to explain how the demo itself is constructed or how it's machinery moves but to demonstrate how MPAS operates.

We can also add some "explainer" articles that discuss how the ocm-controller transforms resources for things like localization and configuration (I mean these things are obvious to us all now at this point but in the context of an MPAS user it might be helpful).

Separate from the conversation about docs, I think part of what you are seeking here could be addressed with tooling. Specifically a command within the `mpas` CLI that would enable MPAS software producers to construct (and verify) MPAS-compliant components. If we can create a guided flow within the CLI (which is entirely possible as the MPAS product construction follows a strong pattern) then we alleviate the need for product authors to consult the docs each time they need to build a MPAS product component.

**Comment by morri-son** [comment]
@phoban01 
> were we to cover all these things in the context of a demo it would no longer really serve the purpose of giving the reader a sense of how to use the system. The focus here should not be to explain how the demo itself is constructed or how its machinery moves but to demonstrate how MPAS operates.
Yeah, that was what I also thought and during writing introduced the idea of making most of the stuff part of the MPAS demo, maybe using a very similar example to point all the details :-)

I like the idea of enhancing the mpas cli with the ability to guide a software producer in creating MPAS compliant OCM components. Especially the pipeline definition in the product description and the relation of its sections to various resources in the OCM component can create quite a headache. If we are able to get support for that into the mpas tooling, that would be great! @phoban01 , would you mind to put this idea into an own issue in the MPAS repo?

**Comment by phoban01** [comment]
Closing with open-component-model/MPAS#132 and open-component-model/MPAS#133
